### ISSUE TITLE
Fails to convert: The value of "offset" is out of range

### ISSUE THREAD

**Issue by Runear** [ozelot379/ConvertMinecraftJavaTextureToBedrockGUI#1]
Conversion was failed

Error:
The value of "offset" is out of range. It must be >= 0 and <= 8188. Received 10788

Pack attempted: Rodrigo 1.14

Let me know if I can help in any way.

When trying to convert an alternate pack (Sapixcraft) it succeeds but results in a 1KB file.

**Comment by Runear** [comment]
Managed to get the alternate pack working by using a folder instead of a zip. Still no dice with the Rodrigo pack.

**Comment by ozelot379** [comment]
@Runear 
Thanks for your issue report

I could debug both bugs
- `The value of "offset" is out of range. It must be >= 0 and <= 8188. Received 10788`: It seems I had misunderstand the weather textures (rain and snow) and in `Rodrigo` seems to use an other format like the default texture pack does - anyway I skip if it's not possible to convert, so at least the rest can be converted and I note this issue and I will reimplement the weather texture converter sometime in the future
- `When trying to convert an alternate pack (Sapixcraft) it succeeds but results in a 1KB file.`: Seems to occur since version 1.4.0 - I revert this a bit so it should work again

I released a new version 1.4.4 - I hope I could help you and I could fix your issues :)

**Comment by Runear** [comment]
Thats awesome, thank you! Just in case it helps I also noticed when I got Sapix to convert (by extracting to a folder) the torch particle effects (if thats what they are... the flame bit) didn't work. Torches emitted light but had no light in the texture, the top was just grey.

That may be a current limitation and I may be misunderstanding what the articles are that are mentioned in the readme, but just in case its a bug I thought I'd mention it.

Thanks for your hard work!

**Comment by ozelot379** [comment]
the particles convert were very bugy, because some texture packs has a mix beetwen Java v1.13 and v1.14, I improved this convert now a bit with v1.4.5

additionally the `Sapixcraft` texture packs seems to use a custom model for the torch to show a burning flame directly over the torch (and the particles) - this can currently not be converted - I don't know if Bedrock supports some what at all

since the torch image of `Sapixcraft` it's self has no 'on' effect, it will only show the stick and the particles, but no on/burning effect, therefore this is a limitation
